#!/usr/bin/env bash
set -exuo pipefail
here="$(realpath $(dirname $0))"
. "$here/config.sh"

cd "$here/.."

if [ ! -e mediawiki ]; then
	git clone https://github.com/wikimedia/mediawiki
fi
cd mediawiki
git checkout "$mediawiki_revision"
git submodule update --init --recursive
